"""Reusable explanatory text for IVIVC approaches, preprocessing, metrics, and reports.

Most routine wording edits should be made in utilities/descriptions.yaml.
This module keeps Python fallback values and formatting helpers for templates,
reports, and generated documentation.
"""

from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover - dependency fallback
    yaml = None



TOOL_PURPOSE_HTML = '''
    <p>Establishing an in vitro-in vivo correlation (IVIVC) can support the evaluation of medical devices that include absorbable polymers by relating in vivo changes in material properties over time to corresponding in vitro test results, such as degradation profiles.</p>
    <p>IVIVCs may help evaluate manufacturing or material changes, support predictions of in vivo performance when modifying an existing device design, and reduce reliance on animal studies during preclinical development.</p>
    <p>This tool is intended to facilitate IVIVC development. The user supplies paired in vitro and in vivo fitting data, and may optionally supply an in vitro prediction dataset. The app applies selected preprocessing steps, fits and compares multiple correlation approaches and model families, evaluates selected performance metrics and cross-validation results, generates fitting and prediction plots, and produces report-ready summaries that can be reviewed and incorporated into external documentation.</p>
'''

TOOL_PURPOSE_TEXT = (
    "Establishing an in vitro-in vivo correlation (IVIVC) can support the "
    "evaluation of medical devices that include absorbable polymers by relating "
    "in vivo changes in material properties over time to corresponding in vitro "
    "test results, such as degradation profiles. IVIVCs may help evaluate "
    "manufacturing or material changes, support predictions of in vivo performance "
    "when modifying an existing device design, and reduce reliance on animal "
    "studies during preclinical development. This tool is intended to facilitate "
    "IVIVC development. The user supplies paired in vitro and in vivo fitting "
    "data, and may optionally supply an in vitro prediction dataset. The app "
    "applies selected preprocessing steps, fits and compares multiple correlation "
    "approaches and model families, evaluates selected performance metrics and "
    "cross-validation results, generates fitting and prediction plots, and "
    "produces report-ready summaries that can be reviewed and incorporated into "
    "external documentation."
)

TOOL_CAPABILITY_SUMMARY = [
    "Apply selected normalization, scaling, and interpolation options to prepare fitting and prediction data.",
    "Fit user-selected IVIVC approaches and model families to paired in vitro and in vivo data.",
    "Calculate selected goodness-of-fit, model-comparison, and cross-validation metrics.",
    "Generate fitting, comparison, and prediction plots with uncertainty displays where supported.",
    "Create report-ready HTML and editable Word summaries for user-selected final models or methods.",
]


APPROACH_DESCRIPTIONS = {
    'approach1': {
        'title': 'Approach 1: Direct Correlation',
        'method_html': '''
            <p>Approach 1 fits a direct relationship between matched in vitro and in vivo time points after preprocessing. The fitted model is then used as a time-scaling function that maps an in vitro time to a predicted in vivo time.</p>
        ''',
        'fit_uncertainty_html': '''
            <p><strong>Parameter estimates:</strong> fitted parameters are reported as estimate &plusmn; standard error. Standard errors are derived from the nonlinear least-squares parameter covariance matrix. Correlations among fitted parameters are retained when uncertainty-aware parameter values are created.</p>
            <p><strong>Fitting plot bands:</strong> shaded 95% prediction bands are generated by Monte Carlo sampling of the fitted parameter covariance matrix. The sampled model variance is combined with the residual variance from the fitted data, then converted to a two-sided interval using a t multiplier when residual degrees of freedom are available.</p>
            <p>These bands describe approximate prediction uncertainty around the fitted relationship, not regulatory acceptance limits. They depend on the fitted model form, local covariance approximation, residual behavior, and preprocessing choices.</p>
        ''',
        'prediction_error_html': '''
            <p><strong>Prediction plot error bars:</strong> when a prediction dataset is supplied, predicted in vivo times are plotted with horizontal error bars. The bars are calculated from the same 95% prediction-band calculation used for the fitted correlation model; the upper and lower bar lengths are the distances from the band mean to the corresponding upper and lower interval bounds at each input prediction time.</p>
            <p>The error bars therefore include propagated fitted-parameter uncertainty and residual/model error from the Approach 1 correlation fit.</p>
        ''',
    },
    'approach2': {
        'title': 'Approach 2: Independent Model Fitting',
        'method_html': '''
            <p>Approach 2 fits the same model family independently to the in vitro and in vivo datasets. With fitting data alone, the report summarizes the two fitted models and their fitted-curve uncertainty. When prediction data are supplied, predictions can be generated by comparing the fitted in vivo and in vitro responses or by comparing fitted characteristic time constants when those values are available.</p>
        ''',
        'fit_uncertainty_html': '''
            <p><strong>Parameter estimates:</strong> each in vitro and in vivo model parameter is reported as estimate &plusmn; standard error. Standard errors are derived from the corresponding nonlinear least-squares covariance matrix, with fitted-parameter correlations retained in uncertainty-aware values.</p>
            <p><strong>Time constants:</strong> tau values, when available, are calculated from the fitted model and parameter covariance. The reported tau uncertainty is the propagated standard uncertainty from that covariance-based calculation.</p>
            <p><strong>Fitting plot bands:</strong> the in vitro and in vivo shaded 95% prediction bands are generated separately. For each fitted model, the app Monte Carlo samples the fitted parameter covariance matrix, combines sampled model variance with residual variance, and converts the resulting standard uncertainty to a two-sided interval using a t multiplier when residual degrees of freedom are available.</p>
        ''',
        'prediction_error_html': '''
            <p><strong>Value-ratio prediction error bars:</strong> uncertainty is propagated from both fitted models. The app samples each model's parameter covariance matrix, calculates the in vivo/in vitro response ratio for each sample, combines ratio variance with residual-based ratio uncertainty, and converts that uncertainty to a two-sided 95% interval. The plotted vertical error bars are scaled from the resulting ratio interval at each prediction time.</p>
            <p><strong>Time-constant-ratio prediction error bars:</strong> when both tau values are valid, uncertainty in each tau is propagated through the tau ratio using uncertainty-aware arithmetic. The standard uncertainty of the scaled prediction time is multiplied by a t value, where available, and plotted as a symmetric horizontal error bar.</p>
            <p>Ratio-based uncertainty can become unstable when the denominator model prediction or denominator time constant is near zero. Predictions in those regions should be interpreted cautiously.</p>
        ''',
    },
    'approach3': {
        'title': 'Approach 3: Direct Mapping',
        'method_html': '''
            <p>Approach 3 uses direct interpolation-based mappings between datasets rather than fitting a parametric model. It can describe value-ratio behavior over time and time-ratio behavior over value ranges. When prediction data are supplied, those mappings can be used to scale prediction values or prediction times.</p>
        ''',
        'fit_uncertainty_html': '''
            <p><strong>Parameter uncertainty:</strong> Approach 3 does not fit a parametric model, so there is no fitted-parameter covariance matrix, no parameter standard errors, and no model-based 95% prediction band.</p>
            <p><strong>Fitting plots:</strong> the plots show interpolation-based ratios/mappings calculated from the preprocessed datasets. They should be interpreted as deterministic mappings from the supplied data and preprocessing choices, not as statistical uncertainty bands.</p>
        ''',
        'prediction_error_html': '''
            <p><strong>Prediction plot error bars:</strong> Approach 3 currently does not generate formal propagated error bars for prediction outputs because no parametric covariance model is fitted.</p>
            <p>Uncertainty is therefore limited to the quality of the input data, preprocessing, interpolation, and the assumption that the observed mapping remains valid for the prediction dataset. Extrapolated points outside the interpolation range are excluded or returned as unavailable.</p>
        ''',
    },
}

PREPROCESSING_DESCRIPTIONS = {
    'normalization': {
        'min_max': {
            'display_name': 'Min-max normalization',
            'description': 'Scales response values to the 0-1 range using the observed minimum and maximum within each dataset.',
        },
        'initial_value': {
            'display_name': 'Initial-value normalization',
            'description': 'Divides response values by the first response value in the corresponding dataset.',
        },
    },
    'scaling': {
        'log_x': {
            'display_name': 'Log10 time scaling',
            'description': 'Applies a base-10 logarithm to time values before fitting or interpolation.',
        },
        'log_y': {
            'display_name': 'Log10 response scaling',
            'description': 'Applies a base-10 logarithm to response values before fitting or interpolation.',
        },
    },
    'interpolation': {
        'none': {
            'display_name': 'No interpolation',
            'description': 'Uses only exact raw alignments. No values are estimated between observations; unavailable aligned positions are marked as missing.',
        },
        'default': {
            'display_name': 'Shared-time interpolation',
            'description': 'Interpolates both datasets onto the common set of experimental time points, using linear interpolation and marking out-of-range values as unavailable.',
        },
        'alternative': {
            'display_name': 'Densified interpolation',
            'description': 'Creates additional linearly spaced points between adjacent observations before interpolation. This can smooth displays and make fitting more stable, but adds more interpolation-derived points that skew statistical comparisons.',
        },
    },
}

METRIC_DESCRIPTIONS = {
    'r_squared': {
        'description': 'Coefficient of determination. Higher values indicate that the model explains more variance in the observed response.',
    },
    'adjusted_r_squared': {
        'description': 'R² adjusted for the number of fitted parameters. Higher values are better and can penalize unnecessary model complexity.',
    },
    'mse': {
        'description': 'Mean squared error between observed and fitted values. Lower values indicate smaller average squared residuals.',
    },
    'rmse': {
        'description': 'Root mean squared error, in the same response units as the fitted data. Lower values indicate smaller typical residuals.',
    },
    'nrmse': {
        'description': 'RMSE normalized by the response standard deviation. Lower values indicate smaller error relative to response variability.',
    },
    'mnrmse': {
        'description': 'RMSE normalized by the response mean. Lower values indicate smaller error relative to the response magnitude.',
    },
    'aic': {
        'description': 'Akaike Information Criterion. Lower values indicate a better fit-complexity tradeoff. AIC is intended for comparison of models fitted to the same dataset, not as an absolute goodness-of-fit measure.',
    },
    'bic': {
        'description': 'Bayesian Information Criterion. Lower values indicate a better fit-complexity tradeoff, with a stronger penalty for additional parameters than AIC. BIC is intended for comparison of models fitted to the same dataset, not as an absolute goodness-of-fit measure.',
    },
}

GRID_SEARCH_DESCRIPTION_HTML = '''
    <p>The app conducts an automated grid search to identify suitable starting parameter values for each model before nonlinear least-squares fitting, avoiding the need for manual parameter tuning. The grid-search settings control the number of candidate starting points, the real-space parameter bounds, and the random seed used for reproducible sampling.</p>
    <p>For each selected model, the app evaluates multiple candidate starting points and uses the best candidate as the starting point for the final curve fit. The grid-search seed makes this random sampling reproducible.</p>
    <p>The grid search makes it more likely for the app to identify suitable starting parameters, but it does not guarantee that the final fitted parameters are the global optimum.</p>
    <p>If fitting fails or appears unstable, consider increasing the number of candidate starting points, widening or narrowing the parameter bounds, changing the random seed, or reviewing whether the selected model is appropriate for the data.</p>
'''

CV_SCHEME_LABELS = {
    'shuffle_split': 'Shuffle split',
    'kfold': 'K-fold',
    'leave_one_out': 'Leave-one-out',
    'none': 'None',
}

ANALYSIS_CONFIG_LABELS = {
    'cv_scheme': 'Cross-validation scheme',
    'cv_n_splits': 'CV splits/folds',
    'cv_test_size': 'ShuffleSplit test size',
    'cv_random_state': 'CV random seed',
    'grid_search_num_points': 'Grid-search random starts',
    'grid_search_num_cores': 'Grid-search CPU cores',
    'grid_search_param_min': 'Grid-search parameter minimum',
    'grid_search_param_max': 'Grid-search parameter maximum',
    'grid_search_random_state': 'Grid-search random seed',
}


MODAL_HELP = {
    'index': {
        'preprocessing_overview_html': '''
            <p>Transform your data before analysis to improve model fitting and comparability. The selected preprocessing choices are included in the results and downloadable Word report.</p>
            <ul>
                <li><strong>Normalization:</strong> optional transformations applied to response values.</li>
                <li><strong>Scaling:</strong> optional mathematical transformations applied to time or response values.</li>
                <li><strong>Interpolation:</strong> methods used to create matched time and response grids for fitting or direct mapping.</li>
            </ul>
            <p>For details on individual preprocessing options, use the help buttons next to Normalization, Scaling, and Interpolation.</p>
        ''',
        'advanced_analysis_overview_html': '''
            <p>Advanced analysis parameters control how the app estimates out-of-sample performance and how it initializes nonlinear model fitting.</p>
            <ul>
                <li><strong>Cross-validation:</strong> controls how fitting data are split into training and holdout subsets for validation metrics.</li>
                <li><strong>Grid search:</strong> controls the automated search for suitable starting parameter values before nonlinear least-squares fitting.</li>
            </ul>
            <p>Default settings are intended to be reasonable starting points. Users may adjust these settings when datasets are small, fits are unstable, or a reproducible analysis configuration is needed.</p>
        ''',
        'cross_validation_html': '''
            <p>Cross-validation estimates how selected fitted models perform on held-out data. It is used for Approaches 1 and 2, where parametric models are fitted.</p>
            <ul>
                <li><strong>Scheme:</strong> selects the splitting method, such as Shuffle split, K-fold, Leave-one-out, or None.</li>
                <li><strong>Splits/folds:</strong> controls the number of repeated splits or folds where applicable.</li>
                <li><strong>Test size:</strong> controls the held-out fraction for Shuffle split.</li>
                <li><strong>Random seed:</strong> makes randomized splitting reproducible.</li>
            </ul>
            <p>Very small datasets may produce unstable or unavailable validation metrics, especially when many folds or large holdout fractions are requested.</p>
        ''',
        'grid_search_html': GRID_SEARCH_DESCRIPTION_HTML,
    },
    'results': {
        'model_comparison_html': '''
            <p>This section summarizes how each fitted model performed under the user-selected metrics. Use these results together with the fitting plots, prediction plots where available, parameter uncertainty, residual behavior, and scientific expectations for the system.</p>
            <p>The metric definitions and better/worse direction are shown in the Model Comparison tab itself, so this help box intentionally provides only a high-level interpretation guide.</p>
            <ul>
                <li>Lower error metrics such as MSE, RMSE, NRMSE, and mean-normalized RMSE generally indicate smaller residuals.</li>
                <li>Higher R² or adjusted R² values generally indicate that the fitted model explains more response variability.</li>
                <li>Lower AIC or BIC values can support relative comparison among models fitted to the same dataset under comparable error assumptions.</li>
            </ul>
            <p>The app does not automatically choose a regulatory final model. The user should review the full set of outputs and select the model or method that is scientifically justified for the intended use.</p>
        ''',
    },
}


def _deep_update(base, updates):
    """Recursively update dictionaries while preserving unspecified defaults."""
    for key, value in updates.items():
        if isinstance(value, dict) and isinstance(base.get(key), dict):
            _deep_update(base[key], value)
        else:
            base[key] = value
    return base


def _load_yaml_descriptions():
    """Load human-editable description text from utilities/descriptions.yaml."""
    if yaml is None:
        return {}

    yaml_path = Path(__file__).with_suffix('.yaml')
    if not yaml_path.exists():
        return {}

    with yaml_path.open('r', encoding='utf-8') as handle:
        return yaml.safe_load(handle) or {}


_DESCRIPTION_CONTENT = _load_yaml_descriptions()

_tool_content = _DESCRIPTION_CONTENT.get('tool', {})
TOOL_PURPOSE_HTML = _tool_content.get('purpose_html', TOOL_PURPOSE_HTML)
TOOL_PURPOSE_TEXT = _tool_content.get('purpose_text', TOOL_PURPOSE_TEXT)
TOOL_CAPABILITY_SUMMARY = _tool_content.get('capability_summary', TOOL_CAPABILITY_SUMMARY)

# Optional YAML overrides for all major reusable description dictionaries. The
# YAML file may contain a partial set of keys; unspecified Python defaults remain
# available so small wording edits do not require duplicating every description.
_deep_update(APPROACH_DESCRIPTIONS, _DESCRIPTION_CONTENT.get('approaches', {}))
_deep_update(PREPROCESSING_DESCRIPTIONS, _DESCRIPTION_CONTENT.get('preprocessing', {}))
_deep_update(METRIC_DESCRIPTIONS, _DESCRIPTION_CONTENT.get('metrics', {}))
_deep_update(CV_SCHEME_LABELS, _DESCRIPTION_CONTENT.get('cv_scheme_labels', {}))
_deep_update(ANALYSIS_CONFIG_LABELS, _DESCRIPTION_CONTENT.get('analysis_config_labels', {}))
GRID_SEARCH_DESCRIPTION_HTML = _DESCRIPTION_CONTENT.get('grid_search_description_html', GRID_SEARCH_DESCRIPTION_HTML)

_modal_content = _DESCRIPTION_CONTENT.get('modal_help', {})
if _modal_content:
    _deep_update(MODAL_HELP, _modal_content)
    GRID_SEARCH_DESCRIPTION_HTML = MODAL_HELP.get('index', {}).get('grid_search_html', GRID_SEARCH_DESCRIPTION_HTML)


def _preprocessing_label(category, key):
    return PREPROCESSING_DESCRIPTIONS.get(category, {}).get(key, {}).get('display_name', key)


def _preprocessing_description(category, key):
    return PREPROCESSING_DESCRIPTIONS.get(category, {}).get(key, {}).get('description', '')


def format_preprocessing_rows(selected_normalizations=None, selected_scalings=None, selected_interpolation=None):
    """Return display-ready preprocessing rows for templates and reports."""
    selections = [
        ('Normalization', 'normalization', selected_normalizations or []),
        ('Scaling', 'scaling', selected_scalings or []),
        ('Interpolation', 'interpolation', selected_interpolation or []),
    ]
    rows = []
    for category_label, category_key, values in selections:
        if values:
            for value in values:
                rows.append({
                    'category': category_label,
                    'name': _preprocessing_label(category_key, value),
                    'description': _preprocessing_description(category_key, value),
                })
        else:
            rows.append({
                'category': category_label,
                'name': 'None',
                'description': 'No option selected for this preprocessing category.',
            })
    return rows


def format_selected_preprocessing_summary(selected_normalizations=None, selected_scalings=None, selected_interpolation=None):
    """Return short human-readable summaries by preprocessing category."""
    return {
        'normalization': '; '.join(_preprocessing_label('normalization', v) for v in (selected_normalizations or [])) or 'None',
        'scaling': '; '.join(_preprocessing_label('scaling', v) for v in (selected_scalings or [])) or 'None',
        'interpolation': '; '.join(_preprocessing_label('interpolation', v) for v in (selected_interpolation or [])) or 'None',
    }


def format_metric_description_rows(metrics, selected_metrics=None):
    """Return display-ready metric description rows.

    The metrics registry supplies display names and better/worse direction. This
    module supplies the explanatory text so the same language can be reused in
    help modals and reports.
    """
    selected_metrics = selected_metrics or list(metrics.keys())
    rows = []
    for metric_key in selected_metrics:
        metric_info = metrics.get(metric_key, {})
        description = METRIC_DESCRIPTIONS.get(metric_key, {}).get('description', '')
        better_direction = metric_info.get('better_direction', '')
        if better_direction == 'higher':
            direction = 'Higher is generally better'
        elif better_direction == 'lower':
            direction = 'Lower is generally better'
        else:
            direction = ''
        rows.append({
            'key': metric_key,
            'name': metric_info.get('display_name', metric_key),
            'direction': direction,
            'description': description,
        })
    return rows


def format_analysis_config_rows(config):
    """Return display-ready (label, value) rows for results and reports."""
    scheme = config.get('cv_scheme', 'shuffle_split')
    rows = []

    for key in [
        'cv_scheme',
        'cv_n_splits',
        'cv_test_size',
        'cv_random_state',
        'grid_search_num_points',
        'grid_search_num_cores',
        'grid_search_param_min',
        'grid_search_param_max',
        'grid_search_random_state',
    ]:
        value = config.get(key, '')
        if key == 'cv_scheme':
            value = CV_SCHEME_LABELS.get(value, value)
        elif key == 'cv_test_size' and scheme != 'shuffle_split':
            value = 'N/A'
        elif key == 'grid_search_num_cores' and value in (None, ''):
            value = 'Auto'
        rows.append((ANALYSIS_CONFIG_LABELS[key], value))

    return rows
