"""Reusable explanatory text for IVIVC approaches, predictions, and reports."""

APPROACH_DESCRIPTIONS = {
    'approach1': {
        'title': 'Approach 1: Direct Correlation',
        'method_html': '''
            <p>Approach 1 fits a direct relationship between matched in vitro and in vivo time points after preprocessing. The fitted model is then used as a time-scaling function that maps an in vitro time to a predicted in vivo time.</p>
        ''',
        'prediction_error_html': '''
            <p>Prediction uncertainty is estimated from the fitted parameter covariance matrix and the model residuals. Parameter uncertainty is propagated through the fitted correlation model, and residual/model error is incorporated when prediction bands are generated.</p>
            <p>These bands are approximate. They assume that the fitted model form is appropriate, the covariance matrix is a reasonable local approximation to parameter uncertainty, and the residual behavior observed in the fitting data is representative of future predictions.</p>
        ''',
    },
    'approach2': {
        'title': 'Approach 2: Independent Model Fitting',
        'method_html': '''
            <p>Approach 2 fits the same model family independently to the in vitro and in vivo datasets. Predictions are generated by comparing the fitted in vivo response to the fitted in vitro response, or by comparing fitted characteristic time constants when those values are available.</p>
        ''',
        'prediction_error_html': '''
            <p>For value-ratio rescaling, uncertainty is propagated from both fitted models. The parameter covariance matrices for the in vitro and in vivo fits are used to estimate uncertainty in each fitted response, and the combined uncertainty is propagated through the in vivo/in vitro ratio.</p>
            <p>For time-constant-ratio rescaling, uncertainty in each estimated time constant is propagated through the tau ratio. This is implemented with uncertainty-aware arithmetic so the predicted in vivo time uncertainty reflects uncertainty in both time constants.</p>
            <p>Ratio-based uncertainty can become unstable when the denominator model prediction or denominator time constant is near zero. Predictions in those regions should be interpreted cautiously.</p>
        ''',
    },
    'approach3': {
        'title': 'Approach 3: Direct Mapping',
        'method_html': '''
            <p>Approach 3 uses direct interpolation-based mappings between datasets rather than fitting a parametric model. It can scale prediction values using an in vivo/in vitro value ratio or scale prediction times using an in vivo/in vitro time ratio.</p>
        ''',
        'prediction_error_html': '''
            <p>Approach 3 is nonparametric and currently does not estimate formal parameter covariance. The app reports the mapped values/times but does not generate model-based error bands for this approach.</p>
            <p>Uncertainty is therefore limited to the quality of the input data, preprocessing, interpolation, and the assumption that the observed mapping remains valid for the prediction dataset. Extrapolated points outside the interpolation range are excluded or returned as unavailable.</p>
        ''',
    },
}

CV_SCHEME_LABELS = {
    'shuffle_split': 'Shuffle split',
    'kfold': 'K-fold',
    'leave_one_out': 'Leave-one-out',
    'none': 'None',
}

ANALYSIS_CONFIG_LABELS = {
    'cv_scheme': 'Cross-validation scheme',
    'cv_n_splits': 'CV splits/folds',
    'cv_test_size': 'ShuffleSplit test size',
    'cv_random_state': 'CV random seed',
    'grid_search_num_points': 'Grid-search random starts',
    'grid_search_num_cores': 'Grid-search CPU cores',
    'grid_search_param_min': 'Grid-search parameter minimum',
    'grid_search_param_max': 'Grid-search parameter maximum',
}


def format_analysis_config_rows(config):
    """Return display-ready (label, value) rows for results and reports."""
    scheme = config.get('cv_scheme', 'shuffle_split')
    rows = []

    for key in [
        'cv_scheme',
        'cv_n_splits',
        'cv_test_size',
        'cv_random_state',
        'grid_search_num_points',
        'grid_search_num_cores',
        'grid_search_param_min',
        'grid_search_param_max',
    ]:
        value = config.get(key, '')
        if key == 'cv_scheme':
            value = CV_SCHEME_LABELS.get(value, value)
        elif key == 'cv_test_size' and scheme != 'shuffle_split':
            value = 'N/A'
        elif key == 'grid_search_num_cores' and value in (None, ''):
            value = 'Auto'
        rows.append((ANALYSIS_CONFIG_LABELS[key], value))

    return rows
