"""Reusable explanatory text for IVIVC approaches, preprocessing, metrics, and reports."""

APPROACH_DESCRIPTIONS = {
    'approach1': {
        'title': 'Approach 1: Direct Correlation',
        'method_html': '''
            <p>Approach 1 fits a direct relationship between matched in vitro and in vivo time points after preprocessing. The fitted model is then used as a time-scaling function that maps an in vitro time to a predicted in vivo time.</p>
        ''',
        'fit_uncertainty_html': '''
            <p><strong>Parameter estimates:</strong> fitted parameters are reported as estimate &plusmn; standard error. Standard errors are derived from the nonlinear least-squares parameter covariance matrix. Correlations among fitted parameters are retained when uncertainty-aware parameter values are created.</p>
            <p><strong>Fitting plot bands:</strong> shaded 95% prediction bands are generated by Monte Carlo sampling of the fitted parameter covariance matrix. The sampled model variance is combined with the residual variance from the fitted data, then converted to a two-sided interval using a t multiplier when residual degrees of freedom are available.</p>
            <p>These bands describe approximate prediction uncertainty around the fitted relationship, not regulatory acceptance limits. They depend on the fitted model form, local covariance approximation, residual behavior, and preprocessing choices.</p>
        ''',
        'prediction_error_html': '''
            <p><strong>Prediction plot error bars:</strong> when a prediction dataset is supplied, predicted in vivo times are plotted with horizontal error bars. The bars are calculated from the same 95% prediction-band calculation used for the fitted correlation model; the upper and lower bar lengths are the distances from the band mean to the corresponding upper and lower interval bounds at each input prediction time.</p>
            <p>The error bars therefore include propagated fitted-parameter uncertainty and residual/model error from the Approach 1 correlation fit.</p>
        ''',
    },
    'approach2': {
        'title': 'Approach 2: Independent Model Fitting',
        'method_html': '''
            <p>Approach 2 fits the same model family independently to the in vitro and in vivo datasets. With fitting data alone, the report summarizes the two fitted models and their fitted-curve uncertainty. When prediction data are supplied, predictions can be generated by comparing the fitted in vivo and in vitro responses or by comparing fitted characteristic time constants when those values are available.</p>
        ''',
        'fit_uncertainty_html': '''
            <p><strong>Parameter estimates:</strong> each in vitro and in vivo model parameter is reported as estimate &plusmn; standard error. Standard errors are derived from the corresponding nonlinear least-squares covariance matrix, with fitted-parameter correlations retained in uncertainty-aware values.</p>
            <p><strong>Time constants:</strong> tau values, when available, are calculated from the fitted model and parameter covariance. The reported tau uncertainty is the propagated standard uncertainty from that covariance-based calculation.</p>
            <p><strong>Fitting plot bands:</strong> the in vitro and in vivo shaded 95% prediction bands are generated separately. For each fitted model, the app Monte Carlo samples the fitted parameter covariance matrix, combines sampled model variance with residual variance, and converts the resulting standard uncertainty to a two-sided interval using a t multiplier when residual degrees of freedom are available.</p>
        ''',
        'prediction_error_html': '''
            <p><strong>Value-ratio prediction error bars:</strong> uncertainty is propagated from both fitted models. The app samples each model's parameter covariance matrix, calculates the in vivo/in vitro response ratio for each sample, combines ratio variance with residual-based ratio uncertainty, and converts that uncertainty to a two-sided 95% interval. The plotted vertical error bars are scaled from the resulting ratio interval at each prediction time.</p>
            <p><strong>Time-constant-ratio prediction error bars:</strong> when both tau values are valid, uncertainty in each tau is propagated through the tau ratio using uncertainty-aware arithmetic. The standard uncertainty of the scaled prediction time is multiplied by a t value, where available, and plotted as a symmetric horizontal error bar.</p>
            <p>Ratio-based uncertainty can become unstable when the denominator model prediction or denominator time constant is near zero. Predictions in those regions should be interpreted cautiously.</p>
        ''',
    },
    'approach3': {
        'title': 'Approach 3: Direct Mapping',
        'method_html': '''
            <p>Approach 3 uses direct interpolation-based mappings between datasets rather than fitting a parametric model. It can describe value-ratio behavior over time and time-ratio behavior over value ranges. When prediction data are supplied, those mappings can be used to scale prediction values or prediction times.</p>
        ''',
        'fit_uncertainty_html': '''
            <p><strong>Parameter uncertainty:</strong> Approach 3 does not fit a parametric model, so there is no fitted-parameter covariance matrix, no parameter standard errors, and no model-based 95% prediction band.</p>
            <p><strong>Fitting plots:</strong> the plots show interpolation-based ratios/mappings calculated from the preprocessed datasets. They should be interpreted as deterministic mappings from the supplied data and preprocessing choices, not as statistical uncertainty bands.</p>
        ''',
        'prediction_error_html': '''
            <p><strong>Prediction plot error bars:</strong> Approach 3 currently does not generate formal propagated error bars for prediction outputs because no parametric covariance model is fitted.</p>
            <p>Uncertainty is therefore limited to the quality of the input data, preprocessing, interpolation, and the assumption that the observed mapping remains valid for the prediction dataset. Extrapolated points outside the interpolation range are excluded or returned as unavailable.</p>
        ''',
    },
}

PREPROCESSING_DESCRIPTIONS = {
    'normalization': {
        'min_max': {
            'display_name': 'Min-max normalization',
            'description': 'Scales response values to the 0-1 range using the observed minimum and maximum within each dataset.',
        },
        'initial_value': {
            'display_name': 'Initial-value normalization',
            'description': 'Divides response values by the first response value in the corresponding dataset.',
        },
    },
    'scaling': {
        'log_x': {
            'display_name': 'Log10 time scaling',
            'description': 'Applies a base-10 logarithm to time values before fitting or interpolation.',
        },
        'log_y': {
            'display_name': 'Log10 response scaling',
            'description': 'Applies a base-10 logarithm to response values before fitting or interpolation.',
        },
    },
    'interpolation': {
        'none': {
            'display_name': 'No interpolation',
            'description': 'Uses only exact raw alignments. No values are estimated between observations; unavailable aligned positions are marked as missing.',
        },
        'default': {
            'display_name': 'Shared-time interpolation',
            'description': 'Interpolates both datasets onto the common set of experimental time points, using linear interpolation and marking out-of-range values as unavailable.',
        },
        'alternative': {
            'display_name': 'Densified interpolation',
            'description': 'Creates additional linearly spaced points between adjacent observations before interpolation. This can smooth displays and make fitting more stable, but adds more interpolation-derived points that skew statistical comparisons.',
        },
    },
}

METRIC_DESCRIPTIONS = {
    'r_squared': {
        'description': 'Coefficient of determination. Higher values indicate that the model explains more variance in the observed response.',
    },
    'adjusted_r_squared': {
        'description': 'R² adjusted for the number of fitted parameters. Higher values are better and can penalize unnecessary model complexity.',
    },
    'mse': {
        'description': 'Mean squared error between observed and fitted values. Lower values indicate smaller average squared residuals.',
    },
    'rmse': {
        'description': 'Root mean squared error, in the same response units as the fitted data. Lower values indicate smaller typical residuals.',
    },
    'nrmse': {
        'description': 'RMSE normalized by the response standard deviation. Lower values indicate smaller error relative to response variability.',
    },
    'mnrmse': {
        'description': 'RMSE normalized by the response mean. Lower values indicate smaller error relative to the response magnitude.',
    },
    'aic': {
        'description': 'Akaike Information Criterion. Lower values indicate a better fit-complexity tradeoff. AIC is intended for relative model comparison on the same dataset, not as an absolute goodness-of-fit measure.',
    },
    'bic': {
        'description': 'Bayesian Information Criterion. Lower values indicate a better fit-complexity tradeoff, with a stronger penalty for additional parameters than AIC. BIC is intended for relative model comparison on the same dataset, not as an absolute goodness-of-fit measure.',
    },
}

GRID_SEARCH_DESCRIPTION_HTML = '''
    <p>The grid-search setting controls the search for initial parameter values before nonlinear least-squares fitting. The minimum and maximum are real-space parameter bounds. Candidate values are sampled logarithmically by magnitude within those bounds, allowing negative and positive starting values when the configured range crosses zero.</p>
    <p>For each selected model, the app evaluates multiple candidate starting points and uses the best candidate as the starting point for the final curve fit. The grid-search seed makes this random starting-point sampling reproducible.</p>
    <p>This initialization step can improve convergence and reduce sensitivity to poor starting values. It is not itself the final fitting algorithm and does not guarantee that the final fitted parameters are the global optimum.</p>
'''

CV_SCHEME_LABELS = {
    'shuffle_split': 'Shuffle split',
    'kfold': 'K-fold',
    'leave_one_out': 'Leave-one-out',
    'none': 'None',
}

ANALYSIS_CONFIG_LABELS = {
    'cv_scheme': 'Cross-validation scheme',
    'cv_n_splits': 'CV splits/folds',
    'cv_test_size': 'ShuffleSplit test size',
    'cv_random_state': 'CV random seed',
    'grid_search_num_points': 'Grid-search random starts',
    'grid_search_num_cores': 'Grid-search CPU cores',
    'grid_search_param_min': 'Grid-search parameter minimum',
    'grid_search_param_max': 'Grid-search parameter maximum',
    'grid_search_random_state': 'Grid-search random seed',
}


def _preprocessing_label(category, key):
    return PREPROCESSING_DESCRIPTIONS.get(category, {}).get(key, {}).get('display_name', key)


def _preprocessing_description(category, key):
    return PREPROCESSING_DESCRIPTIONS.get(category, {}).get(key, {}).get('description', '')


def format_preprocessing_rows(selected_normalizations=None, selected_scalings=None, selected_interpolation=None):
    """Return display-ready preprocessing rows for templates and reports."""
    selections = [
        ('Normalization', 'normalization', selected_normalizations or []),
        ('Scaling', 'scaling', selected_scalings or []),
        ('Interpolation', 'interpolation', selected_interpolation or []),
    ]
    rows = []
    for category_label, category_key, values in selections:
        if values:
            for value in values:
                rows.append({
                    'category': category_label,
                    'name': _preprocessing_label(category_key, value),
                    'description': _preprocessing_description(category_key, value),
                })
        else:
            rows.append({
                'category': category_label,
                'name': 'None',
                'description': 'No option selected for this preprocessing category.',
            })
    return rows


def format_selected_preprocessing_summary(selected_normalizations=None, selected_scalings=None, selected_interpolation=None):
    """Return short human-readable summaries by preprocessing category."""
    return {
        'normalization': '; '.join(_preprocessing_label('normalization', v) for v in (selected_normalizations or [])) or 'None',
        'scaling': '; '.join(_preprocessing_label('scaling', v) for v in (selected_scalings or [])) or 'None',
        'interpolation': '; '.join(_preprocessing_label('interpolation', v) for v in (selected_interpolation or [])) or 'None',
    }


def format_metric_description_rows(metrics, selected_metrics=None):
    """Return display-ready metric description rows.

    The metrics registry supplies display names and better/worse direction. This
    module supplies the explanatory text so the same language can be reused in
    help modals and reports.
    """
    selected_metrics = selected_metrics or list(metrics.keys())
    rows = []
    for metric_key in selected_metrics:
        metric_info = metrics.get(metric_key, {})
        description = METRIC_DESCRIPTIONS.get(metric_key, {}).get('description', '')
        better_direction = metric_info.get('better_direction', '')
        if better_direction == 'higher':
            direction = 'Higher is generally better'
        elif better_direction == 'lower':
            direction = 'Lower is generally better'
        else:
            direction = ''
        rows.append({
            'key': metric_key,
            'name': metric_info.get('display_name', metric_key),
            'direction': direction,
            'description': description,
        })
    return rows


def format_analysis_config_rows(config):
    """Return display-ready (label, value) rows for results and reports."""
    scheme = config.get('cv_scheme', 'shuffle_split')
    rows = []

    for key in [
        'cv_scheme',
        'cv_n_splits',
        'cv_test_size',
        'cv_random_state',
        'grid_search_num_points',
        'grid_search_num_cores',
        'grid_search_param_min',
        'grid_search_param_max',
        'grid_search_random_state',
    ]:
        value = config.get(key, '')
        if key == 'cv_scheme':
            value = CV_SCHEME_LABELS.get(value, value)
        elif key == 'cv_test_size' and scheme != 'shuffle_split':
            value = 'N/A'
        elif key == 'grid_search_num_cores' and value in (None, ''):
            value = 'Auto'
        rows.append((ANALYSIS_CONFIG_LABELS[key], value))

    return rows
