#!/usr/bin/env python3
"""Generate README.md and docs/user_guide.md from reusable app descriptions.

Run from the repository root:

    python utilities/generate_user_guide.py

The generator reads user-facing descriptions from utilities/descriptions.py,
which can load routine wording changes from utilities/descriptions.yaml, and
combines them with the live model, metric, and preprocessing registries when
available. Keep routine wording changes in utilities/descriptions.yaml where
possible, then rerun this script to refresh the Markdown documentation.
"""
from __future__ import annotations

from html import unescape
from pathlib import Path
from textwrap import dedent
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

try:
    from metrics import metrics
except Exception:  # pragma: no cover - documentation fallback
    metrics = {}

try:
    from models import approaches, models
except Exception:  # pragma: no cover - documentation fallback
    approaches = {
        "approach1": {"display_name": "Approach 1", "models": []},
        "approach2": {"display_name": "Approach 2", "models": []},
        "approach3": {"display_name": "Approach 3", "models": []},
    }
    models = {}

try:
    from preprocessing import preprocessing_options
except Exception:  # pragma: no cover - documentation fallback
    preprocessing_options = {"normalization": {}, "scaling": {}, "interpolation": {}}

from utilities.descriptions import (  # noqa: E402
    ANALYSIS_CONFIG_LABELS,
    ANALYSIS_PARAMETER_DESCRIPTIONS,
    APPROACH_DESCRIPTIONS,
    CROSS_VALIDATION_DESCRIPTION_HTML,
    CV_SCHEME_DESCRIPTIONS,
    CV_SCHEME_LABELS,
    GRID_SEARCH_DESCRIPTION_HTML,
    METRIC_DESCRIPTIONS,
    PREPROCESSING_DESCRIPTIONS,
    RELATIVE_MODEL_EVIDENCE_TEXT,
    TOOL_CAPABILITY_SUMMARY,
    TOOL_PURPOSE_TEXT,
)

README_PATH = ROOT / "README.md"
GUIDE_PATH = ROOT / "docs" / "user_guide.md"
APPENDICES_DIR = ROOT / "docs" / "appendices"
APP_DESCRIPTION = TOOL_PURPOSE_TEXT


def html_to_text(value: str) -> str:
    """Convert short HTML description fragments to Markdown-friendly text."""
    if not value:
        return ""
    text = value.strip()
    text = re.sub(r"</p>\s*<p>", "\n\n", text)
    text = re.sub(r"<br\s*/?>", "\n", text)
    text = re.sub(r"<[^>]+>", "", text)
    text = unescape(text)
    text = re.sub(r"[ \t]+", " ", text)
    return text.strip()




def html_to_markdown_block(value: str) -> str:
    """Convert short HTML fragments to paragraph-oriented Markdown."""
    if not value:
        return ""
    text = value.strip()
    text = re.sub(r"<strong>(.*?)</strong>", r"**\1**", text, flags=re.S)
    text = re.sub(r"</p>\s*<p>", "\n\n", text)
    text = re.sub(r"^\s*<p>", "", text)
    text = re.sub(r"</p>\s*$", "", text)
    text = re.sub(r"<br\s*/?>", "\n", text)
    text = re.sub(r"<[^>]+>", "", text)
    text = unescape(text)
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def escape_md_table(value) -> str:
    text = str(value)
    text = text.replace("\n\n", "<br><br>").replace("\n", "<br>")
    return text.replace("|", "\\|")


def heading(level: int, text: str) -> str:
    return f"{'#' * level} {text}\n\n"


def table(headers: list[str], rows: list[list[object]]) -> str:
    lines = ["| " + " | ".join(headers) + " |"]
    lines.append("| " + " | ".join("---" for _ in headers) + " |")
    for row in rows:
        lines.append("| " + " | ".join(escape_md_table(cell) for cell in row) + " |")
    return "\n".join(lines) + "\n\n"


def generated_notice() -> str:
    return "<!-- Generated by utilities/generate_user_guide.py. Edit routine wording in utilities/descriptions.yaml where possible. Long-form appendices are sourced from docs/appendices/. -->\n\n"


def read_appendices() -> str:
    """Return long-form Markdown appendices to include in the generated guide."""
    if not APPENDICES_DIR.exists():
        return ""

    appendix_sections = []
    for appendix_path in sorted(APPENDICES_DIR.glob("*.md")):
        text = appendix_path.read_text(encoding="utf-8").strip()
        if text:
            appendix_sections.append(text)

    if not appendix_sections:
        return ""

    return "\n\n---\n\n" + "\n\n---\n\n".join(appendix_sections) + "\n"


def user_guide_metadata() -> str:
    """Return Pandoc YAML metadata for the generated user guide."""
    return dedent(r"""
        ---
        title: "IVIVC App User Guide"
        author: ""
        date: ""
        header-includes:
          - \usepackage{fancyhdr}
          - \pagestyle{fancy}
          - \fancyhf{}
          - \lhead{IVIVC App User Guide}
          - \rhead{\thepage}
          - \fancypagestyle{plain}{\fancyhf{}\renewcommand{\headrulewidth}{0pt}}
        ---
        """
    ).lstrip() + "\n"


def preprocessing_label(category: str, key: str) -> str:
    item = PREPROCESSING_DESCRIPTIONS.get(category, {}).get(key, {})
    return item.get("display_name") or item.get("short_name") or key.replace("_", " ").title()


def preprocessing_description(category: str, key: str) -> str:
    return PREPROCESSING_DESCRIPTIONS.get(category, {}).get(key, {}).get("description", "")


def metric_description(metric_key: str) -> str:
    return METRIC_DESCRIPTIONS.get(metric_key, {}).get("description", "")


def direction_label(direction: str) -> str:
    if direction == "higher":
        return "Higher is generally better"
    if direction == "lower":
        return "Lower is generally better"
    return direction or ""


def analysis_parameter_description(key: str) -> str:
    return ANALYSIS_PARAMETER_DESCRIPTIONS.get(key, "")


def build_readme() -> str:
    capabilities_md = "\n".join(f"        - {item}" for item in TOOL_CAPABILITY_SUMMARY)
    return generated_notice() + dedent(
        f"""
        # IVIVC App

        {APP_DESCRIPTION}

        ## Quick start

        1. Install the Python dependencies listed in `requirements.txt`.
        2. Start the Flask app with `python app.py`.
        3. Open the local URL shown by Flask.
        4. Upload a fitting dataset with four columns: in vitro time, in vitro value, in vivo time, and in vivo value.
        5. Select approaches, models, preprocessing options, metrics, and analysis parameters.
        6. Optionally upload a two-column in vitro prediction dataset.
        7. Review model outputs, plots, downloadable spreadsheets, and report outputs.

        ## Main inputs

        - **Fitting dataset:** required four-column dataset used for model fitting.
        - **Prediction dataset:** optional two-column in vitro dataset used to generate predictions after fitting.
        - **Approaches/models:** mathematical methods and candidate functions to evaluate.
        - **Preprocessing:** optional normalization, scaling, and interpolation settings.
        - **Metrics:** goodness-of-fit and model-comparison metrics.
        - **Analysis parameters:** cross-validation and grid-search settings.

        ## What the app does

{capabilities_md}

        ## Main outputs

        - Preprocessing summaries and plots.
        - Fitted model parameters and performance metrics.
        - Cross-validation metrics for supported approaches.
        - Model-comparison tables.
        - Prediction plots and tables when a prediction dataset is supplied.
        - Downloadable spreadsheet outputs and report outputs where enabled.

        ## User guide

        See [`docs/user_guide.md`](docs/user_guide.md) for detailed descriptions of inputs, options, methods, and outputs.

        ## Updating documentation text

        User-facing descriptions are centralized in `utilities/descriptions.py`, with routine wording overrides in `utilities/descriptions.yaml`. After editing those descriptions, regenerate the guide with:

        ```bash
        python utilities/generate_user_guide.py
        ```

        To create a PDF from the Markdown guide, one option is:

        ```bash
        pandoc docs/user_guide.md -o docs/user_guide.pdf
        ```
        """
    ).lstrip()


def build_user_guide() -> str:
    parts: list[str] = [user_guide_metadata(), generated_notice()]
    parts.append(APP_DESCRIPTION + "\n\n")

    parts.append(heading(2, "1. What the app does"))
    for item in TOOL_CAPABILITY_SUMMARY:
        parts.append(f"- {item}\n")
    parts.append("\n")

    parts.append(heading(2, "2. Input datasets"))
    parts.append(table(
        ["Input", "Description"],
        [
            ["Fitting dataset", "Required four-column dataset used to establish the in vitro/in vivo relationship. Columns are interpreted as in vitro time, in vitro value, in vivo time, and in vivo value."],
            ["Prediction dataset", "Optional two-column in vitro dataset used after fitting to generate in vivo predictions. Columns are interpreted as in vitro time and in vitro value."],
        ],
    ))
    parts.append("For Excel workbooks, select the sheet containing the relevant data. For CSV files, the first columns are read directly in the order described above.\n\n")

    parts.append(heading(2, "3. Analysis approaches and models"))
    approach_rows = []
    for approach_key, approach_info in approaches.items():
        desc = APPROACH_DESCRIPTIONS.get(approach_key, {})
        model_names = [models[m].get("display_name", m) for m in approach_info.get("models", []) if m in models]
        model_text = ", ".join(model_names) if model_names else "No parametric model selection"
        method_text = html_to_text(desc.get("method_html", ""))
        approach_rows.append([
            desc.get("title", approach_info.get("display_name", approach_key)),
            method_text,
            model_text,
        ])
    parts.append(table(["Approach", "Description", "Available models"], approach_rows))

    parts.append(heading(2, "4. Preprocessing options"))
    for category in ["normalization", "scaling", "interpolation"]:
        parts.append(heading(3, category.title()))
        keys = list(preprocessing_options.get(category, {}).keys())
        if not keys:
            keys = list(PREPROCESSING_DESCRIPTIONS.get(category, {}).keys())
        rows = [[preprocessing_label(category, key), f"`{key}`", preprocessing_description(category, key)] for key in keys]
        parts.append(table(["Option", "Internal key", "Description"], rows))

    parts.append(heading(2, "5. Relative model evidence"))
    parts.append(RELATIVE_MODEL_EVIDENCE_TEXT + "\n\n")
    parts.append(table(
        ["Evidence summary", "Interpretation"],
        [
            ["Delta AICc / Delta AIC / Delta BIC", "Difference from the lowest value in the displayed candidate set. Values near 0 indicate similar relative support; larger values indicate lower support relative to the leading candidate under that criterion."],
            ["AICc or BIC weight", "Normalized relative-support value across the candidate models in the displayed evidence table. Weights are relative, not absolute probabilities that a model is true."],
            ["Evidence ratio", "Ratio of the highest evidence weight to the model's evidence weight. Larger ratios indicate less relative support compared with the highest-weighted model in the set."],
            ["Interpretation badge", "Neutral rule-of-thumb label based on the displayed delta values. The label supports user review and is not an app recommendation."],
        ],
    ))

    parts.append(heading(2, "6. Cross-validation options"))
    parts.append(html_to_text(CROSS_VALIDATION_DESCRIPTION_HTML) + "\n\n")
    parts.append(table(
        ["Scheme", "Internal key", "Description"],
        [[label, f"`{key}`", CV_SCHEME_DESCRIPTIONS.get(key, "")] for key, label in CV_SCHEME_LABELS.items()],
    ))
    cv_rows = []
    for key, label in ANALYSIS_CONFIG_LABELS.items():
        if key.startswith("cv_"):
            cv_rows.append([label, f"`{key}`", analysis_parameter_description(key)])
    parts.append(table(["Parameter", "Internal key", "Description"], cv_rows))

    parts.append(heading(2, "7. Grid-search initialization"))
    parts.append(html_to_text(GRID_SEARCH_DESCRIPTION_HTML) + "\n\n")
    grid_rows = []
    for key, label in ANALYSIS_CONFIG_LABELS.items():
        if key.startswith("grid_search"):
            grid_rows.append([label, f"`{key}`", analysis_parameter_description(key)])
    parts.append(table(["Parameter", "Internal key", "Description"], grid_rows))

    parts.append(heading(2, "8. Performance metrics"))
    metric_rows = []
    for metric_key, metric_info in metrics.items():
        metric_rows.append([
            metric_info.get("display_name", metric_key),
            f"`{metric_key}`",
            direction_label(metric_info.get("better_direction", "")),
            metric_description(metric_key),
        ])
    if not metric_rows:
        for metric_key, desc in METRIC_DESCRIPTIONS.items():
            metric_rows.append([metric_key.replace("_", " ").title(), f"`{metric_key}`", "", desc.get("description", "")])
    parts.append(table(["Metric", "Internal key", "Preferred direction", "Description"], metric_rows))

    parts.append(heading(2, "9. Uncertainty and error bars"))
    parts.append(
        "The following descriptions summarize how fitted-parameter uncertainty, fitting-plot bands, "
        "and prediction error bars are calculated or interpreted for each approach.\n\n"
    )
    for approach_key, desc in APPROACH_DESCRIPTIONS.items():
        title = desc.get("title", approach_key)
        fit_text = html_to_markdown_block(desc.get("fit_uncertainty_html", ""))
        prediction_text = html_to_markdown_block(desc.get("prediction_error_html", ""))
        parts.append(heading(3, title))
        if fit_text:
            parts.append(f"**Fitting uncertainty**\n\n{fit_text}\n\n")
        if prediction_text:
            parts.append(f"**Prediction uncertainty**\n\n{prediction_text}\n\n")

    parts.append(heading(2, "10. Outputs"))
    parts.append(table(
        ["Output", "Description"],
        [
            ["Preprocessing outputs", "Processed data tables and plots showing the data used for fitting and prediction."],
            ["Model fitting outputs", "Parameter estimates, parameter standard errors where available, fitted plots, and selected performance metrics."],
            ["Model comparison outputs", "Tables comparing selected approaches, models, metrics, and cross-validation summaries."],
            ["Prediction outputs", "Prediction plots and downloadable tables when a prediction dataset is supplied and the selected method can be applied."],
            ["Selected model & summary of outputs", "User-selected report summaries and optional Word report export for incorporation into external documentation."],
        ],
    ))
    parts.append("Output availability depends on the selected approaches, whether fitting succeeds, and whether a prediction dataset was supplied.\n\n")

    parts.append(heading(2, "11. Command-line interface"))
    parts.append("The repository includes `cli.py` for batch-oriented fitting from the command line. Use `python cli.py --help` to see available arguments for input files, approaches, models, metrics, preprocessing options, cross-validation settings, and grid-search settings. The internal keys specified in this user guide are used as settings with `cli.py`.\n\n")

    parts.append(heading(2, "12. Regenerating this guide"))
    parts.append(dedent(
        """
        Most descriptive text in this guide is generated from `utilities/descriptions.py`, with routine wording overrides in `utilities/descriptions.yaml`. Long-form appendices are sourced from Markdown files in `docs/appendices/`. After editing those files, regenerate the Markdown files with:

        ```bash
        python utilities/generate_user_guide.py
        ```

        To generate a PDF, use a Markdown-to-PDF tool such as Pandoc:

        ```bash
        pandoc docs/user_guide.md -o docs/user_guide.pdf
        ```
        """
    ).strip() + "\n")

    parts.append(read_appendices())

    return "".join(parts)


def main() -> None:
    GUIDE_PATH.parent.mkdir(parents=True, exist_ok=True)
    README_PATH.write_text(build_readme(), encoding="utf-8")
    GUIDE_PATH.write_text(build_user_guide(), encoding="utf-8")
    print(f"Wrote {README_PATH.relative_to(ROOT)}")
    print(f"Wrote {GUIDE_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
